---

- name:  Automated Distribution of ThousandEyes Proxy SSL Certificates
  hosts: cat9k
  gather_facts: no

  tasks:
    - include_vars: params.yml

    - name: Checking if App is running
      cisco.ios.ios_command:
        commands: "show app-hosting list | i {{te_appid}}"
      register: appid_presence

    - block:
      - name: Copying certificate pem file to target
        ansible.netcommon.net_put:
          src: '{{pem_dir}}{{item}}'
          protocol: scp
          dest: '{{flash_path}}:/{{item}}'
        with_items: '{{pem_file}}'

      - block:
         - name: Injecting certificate pem into running TE container
           cisco.ios.ios_command:
             commands:
             - command: 'app-hosting data appid {{te_appid}} copy {{flash_path}}:{{item}} {{item}}'
           with_items: '{{pem_file}}'
           failed_when: false
        rescue:
        - name: Rescue block
          debug:
            msg: 'File {{item.item}}  exists on {{te_appid}}. Skipping...'

      - name: Moving certificate in running TE container to cert store folder
        cisco.ios.ios_command:
          commands:
          - command: 'app-hosting connect appid {{te_appid}} session /bin/bash'
          - command: 'cp /iox_data/appdata/{{item}} /usr/share/ca-certificates/{{item}}'
          - command: 'grep -qxF {{item}} /etc/ca-certificates.conf || echo {{item}} >> /etc/ca-certificates.conf'
          - command: 'update-ca-certificates'
          - command: 'exit'
        with_items: '{{pem_file}}'

      when: appid_presence.stdout_lines is match(".*RUNNING")
